apiVersion: 1
datasources:
- name: Traefik
  type: prometheus
  access: proxy
  url: http://promotheus:9090
  isDefault: true
  jsonData:
    timeInterval: "5s"
    httpMethod: "GET"
    # httpHeaderName1: "Authorization"
    # httpHeaderValue1: "Bearer <your_token>"
    tlsSkipVerify: true